format = '''
$username$hostname$directory $git_branch$kubernetes$time
[>](dimmed blue bold) ''' # there has to be a another way #TODO

[status]
disabled = false

[kubernetes]
format = '[$context](dimmed blue) '
disabled = false
# detect_files = ['.k8s']

[username]
style_user = 'dimmed blue'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '(dimmed blue)@[$hostname](dimmed blue)'
disabled = false

[directory]
style = 'dimmed green'
format = ' [$path]($style)'
truncation_length = 8
truncation_symbol = '…/'

[time]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
